### ISSUE TITLE
考虑下更好的聊天项目？

### ISSUE THREAD

**Issue by zirconline** [valetzx/chatroomonreplit#1]
不得不说，这个使用node.js实现的聊天室十分原始，实用价值不高。可否考虑研究 matrix 项目，有go 和 Python 实现的后端。

参考：
[去中心化通讯协议 Matrix | Easton Man's Blog](https://blog.eastonman.com/blog/2020/10/matrix/) 

[matrix踩坑记](https://yingziwu.gitlab.io/posts/matrix-deployment-process-part-1/) 

[开源框架 Matrix-Dendrite 搭建聊天服务器的详细过程_docker](https://m.jb51.net/article/240365.htm)

**Comment by valetzx** [comment]
您好，这个项目是为了在 https://replit.com/ 快捷部署，而Matrix最方便的部署方式为Docker，实用价值看个人，如果有需求的可以在Heroku或其他PaaS部署Matrix

**Comment by zirconline** [comment]
Fine.我认同。
